<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcus Fillipe e Gustavo">

<title>Relatório 01 - Fundamentos Iniciais da Linguagem R e Estatística Básica</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> 📌 Introdução</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">2</span> 🎯 Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-geral" id="toc-objetivo-geral" class="nav-link" data-scroll-target="#objetivo-geral"><span class="header-section-number">2.1</span> Objetivo geral</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos específicos</a></li>
  </ul></li>
  <li><a href="#fundamentação-teórica" id="toc-fundamentação-teórica" class="nav-link" data-scroll-target="#fundamentação-teórica"><span class="header-section-number">3</span> 📚 Fundamentação Teórica</a>
  <ul class="collapse">
  <li><a href="#fundamentos-do-r-e-do-rstudio" id="toc-fundamentos-do-r-e-do-rstudio" class="nav-link" data-scroll-target="#fundamentos-do-r-e-do-rstudio"><span class="header-section-number">3.1</span> Fundamentos do R e do RStudio</a></li>
  <li><a href="#gerenciamento-dos-objetos-e-do-diretório-de-trabalho." id="toc-gerenciamento-dos-objetos-e-do-diretório-de-trabalho." class="nav-link" data-scroll-target="#gerenciamento-dos-objetos-e-do-diretório-de-trabalho."><span class="header-section-number">3.2</span> Gerenciamento dos objetos e do diretório de trabalho.</a></li>
  <li><a href="#conceitos-fundamentais-da-estatística" id="toc-conceitos-fundamentais-da-estatística" class="nav-link" data-scroll-target="#conceitos-fundamentais-da-estatística"><span class="header-section-number">3.3</span> Conceitos fundamentais da estatística</a></li>
  <li><a href="#notação-de-somatório" id="toc-notação-de-somatório" class="nav-link" data-scroll-target="#notação-de-somatório"><span class="header-section-number">3.4</span> Notação de Somatório</a></li>
  <li><a href="#organização-dos-dados-e-distribuição-de-frequências" id="toc-organização-dos-dados-e-distribuição-de-frequências" class="nav-link" data-scroll-target="#organização-dos-dados-e-distribuição-de-frequências"><span class="header-section-number">3.5</span> Organização dos dados e Distribuição de Frequências</a></li>
  <li><a href="#medidas-de-posição" id="toc-medidas-de-posição" class="nav-link" data-scroll-target="#medidas-de-posição"><span class="header-section-number">3.6</span> Medidas de Posição</a></li>
  <li><a href="#medidas-de-dispersão" id="toc-medidas-de-dispersão" class="nav-link" data-scroll-target="#medidas-de-dispersão"><span class="header-section-number">3.7</span> Medidas de dispersão</a></li>
  <li><a href="#tópico-adicional-medidas-de-forma-assimetria-e-curtose" id="toc-tópico-adicional-medidas-de-forma-assimetria-e-curtose" class="nav-link" data-scroll-target="#tópico-adicional-medidas-de-forma-assimetria-e-curtose"><span class="header-section-number">3.8</span> Tópico Adicional: Medidas de Forma (Assimetria e Curtose)</a></li>
  </ul></li>
  <li><a href="#metodologia-e-estudo-de-caso" id="toc-metodologia-e-estudo-de-caso" class="nav-link" data-scroll-target="#metodologia-e-estudo-de-caso"><span class="header-section-number">4</span> ⚙️ Metodologia e Estudo de Caso</a>
  <ul class="collapse">
  <li><a href="#inicialização-e-entrada-dos-dados" id="toc-inicialização-e-entrada-dos-dados" class="nav-link" data-scroll-target="#inicialização-e-entrada-dos-dados"><span class="header-section-number">4.1</span> Inicialização e Entrada dos Dados</a></li>
  <li><a href="#tabulação-de-frequências-consciência-do-processo" id="toc-tabulação-de-frequências-consciência-do-processo" class="nav-link" data-scroll-target="#tabulação-de-frequências-consciência-do-processo"><span class="header-section-number">4.2</span> Tabulação de Frequências (Consciência do Processo)</a></li>
  <li><a href="#síntese-descritiva-posição-dispersão-e-forma" id="toc-síntese-descritiva-posição-dispersão-e-forma" class="nav-link" data-scroll-target="#síntese-descritiva-posição-dispersão-e-forma"><span class="header-section-number">4.3</span> Síntese Descritiva: Posição, Dispersão e Forma</a></li>
  <li><a href="#apresentação-gráfica-e-decisão-de-engenharia" id="toc-apresentação-gráfica-e-decisão-de-engenharia" class="nav-link" data-scroll-target="#apresentação-gráfica-e-decisão-de-engenharia"><span class="header-section-number">4.4</span> Apresentação Gráfica e Decisão de Engenharia</a></li>
  </ul></li>
  <li><a href="#considerações-finais" id="toc-considerações-finais" class="nav-link" data-scroll-target="#considerações-finais"><span class="header-section-number">5</span> 🧠 Considerações Finais</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><span class="header-section-number">6</span> 📖 Referências</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<div class="logos" style="display: flex; justify-content: center; align-items: center; height: 200px; gap: 20px;">
  <a href="https://ufsj.edu.br">
    <img src="imagens/ufsj.png" width="220px">
  </a>
  <a href="https://ufsj.edu.br/defim">
    <img src="imagens/defim.png" width="220px">
  </a>
</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Relatório 01 - Fundamentos Iniciais da Linguagem R e Estatística Básica</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar o código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder o código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver o código fonte</a></li></ul></div></div>
<p class="subtitle lead"><a href="https://bendeivide.github.io/courses/epaec/" target="_blank">Estatística e Probabilidade</a> <br> <a href="https://bendeivide.github.io" target="_blank">Prof.&nbsp;Ben Dêivide (DEFIM/CAP/UFSJ)</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marcus Fillipe e Gustavo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">24/08/2026, 17:10</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">1</span> 📌 Introdução</h2>
<p>A utilização de métodos estatísticos é de grande importância para o tratamento e a interpretação de informações obtidas em diferentes áreas da Engenharia. Na Engenharia Civil, esses métodos podem ser empregados na avaliação de resultados experimentais, no controle de qualidade, em levantamentos técnicos e no estudo das propriedades e do comportamento de materiais. A análise dos dados permite identificar características, tendências e variações, fornecendo subsídios para uma interpretação mais adequada dos resultados e para a tomada de decisões.</p>
<p>A Estatística Descritiva permite organizar e apresentar os dados de forma simplificada, facilitando sua compreensão. Para isso, podem ser utilizadas tabelas e gráficos, além de medidas de posição e dispersão. Indicadores como assimetria e curtose também auxiliam na avaliação da distribuição dos dados. Dessa forma, é possível obter uma visão geral do conjunto analisado e identificar comportamentos que podem ser relevantes para o estudo.</p>
<p>O desenvolvimento de ferramentas computacionais também contribui para tornar as análises estatísticas mais práticas e eficientes. Nesse contexto, a linguagem R apresenta diversos recursos destinados ao processamento e à análise de dados, enquanto o RStudio oferece um ambiente que facilita a elaboração e execução dos comandos, bem como a visualização dos resultados e gráficos. A utilização de pacotes específicos, como o leem, permite ampliar as funcionalidades disponíveis e auxiliar na realização dos procedimentos estatísticos.</p>
<p>Diante disso, esta prática consiste na aplicação de conceitos de Estatística Descritiva utilizando a linguagem R, o ambiente RStudio e o pacote leem. Os procedimentos serão aplicados a dados relacionados à Engenharia Civil, envolvendo sua organização, representação e análise. A atividade busca, portanto, associar os conceitos estatísticos aos recursos computacionais, possibilitando uma interpretação mais clara e fundamentada dos resultados obtidos.</p>
</section>
<section id="objetivos" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="objetivos"><span class="header-section-number">2</span> 🎯 Objetivos</h2>
<section id="objetivo-geral" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="objetivo-geral"><span class="header-section-number">2.1</span> Objetivo geral</h3>
<p>Aplicar os fundamentos da Estatística Descritiva e da programação em R na análise de dados voltados à Engenharia Civil. A prática fundamenta-se nos quatro primeiros capítulos do livro <em>Estatística &amp; Probabilidade Aplicada às Engenharias e Ciências (EPAEC)</em> de <span class="citation" data-cites="batista2024epaec">Oliveira Batista (<a href="#ref-batista2024epaec" role="doc-biblioref">2024</a>)</span>, integrando a teoria matemática à execução computacional por meio do pacote <code>leem</code>, visando a organização, representação e a discussão crítica de um estudo de caso prático.</p>
</section>
<section id="objetivos-específicos" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos específicos</h3>
<ul>
<li>Introduzir os conceitos de base da linguagem R e do RStudio (sintaxe, semântica e gerenciamento de objetos), fundamentados tanto no livro de <span class="citation" data-cites="Rbasico2022">Batista e Oliveira (<a href="#ref-Rbasico2022" role="doc-biblioref">2022</a>)</span>, quanto nas 26 vídeo-aulas do curso R Básico.</li>
<li>Revisar os conceitos iniciais da estatística (população, amostra e variáveis), além da notação de somatórios (Capítulo 1 do EPAEC).</li>
<li>Aplicar técnicas de coleta, organização, tabulação e apresentação gráfica de dados quantitativos (Capítulo 2 do EPAEC).</li>
<li>Compreender as formulações matemáticas e o significado prático das principais Medidas de Posição: média, mediana e moda (Capítulo 3 do EPAEC).</li>
<li>Compreender e calcular as Medidas de Dispersão: amplitude, variância, desvio padrão, coeficiente de variação e erro padrão (Capítulo 4 do EPAEC).</li>
<li>Pesquisar, definir e implementar o cálculo das Medidas de Forma (Assimetria e Curtose), interpretando o formato das distribuições estatísticas.</li>
<li>Utilizar o pacote <code>leem</code> para estruturar um banco de dados de Engenharia Civil (Controle de Compactação de Solos), gerando análises numéricas e gráficas exequíveis.</li>
<li>Discutir o diagnóstico de engenharia gerado pelos dados, avaliando o atendimento a critérios de projeto e a qualidade de execução de um serviço hipotético.</li>
</ul>
<hr>
</section>
</section>
<section id="fundamentação-teórica" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="fundamentação-teórica"><span class="header-section-number">3</span> 📚 Fundamentação Teórica</h2>
<section id="fundamentos-do-r-e-do-rstudio" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="fundamentos-do-r-e-do-rstudio"><span class="header-section-number">3.1</span> Fundamentos do R e do RStudio</h3>
<p>O R é um ambiente computacional de código aberto destinado à manipulação e análise de dados, realização de cálculos estatísticos e produção de gráficos. Além de suas funções nativas, permite a criação e o compartilhamento de novas funcionalidades por meio de pacotes desenvolvidos pela comunidade.</p>
<p>O projeto foi iniciado em 1991, na Nova Zelândia, pelos pesquisadores Ross Ihaka e Robert Gentleman, tendo sua primeira versão oficial disponibilizada em 1995. Em 1997, foi criado o CRAN (Comprehensive R Archive Network), responsável pela distribuição do R, de sua documentação e de milhares de pacotes.</p>
<p>O RStudio é uma IDE (Integrated Development Environment) desenvolvida para facilitar a utilização do R. Ele não substitui o R, mas oferece uma interface organizada para escrita e execução de códigos. Sua estrutura reúne, principalmente, o editor de scripts, o console, o painel de ambiente e histórico e as áreas destinadas a arquivos, gráficos, pacotes e ajuda.</p>
<section id="princípios-fundamentais-do-r" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="princípios-fundamentais-do-r"><span class="header-section-number">3.1.1</span> Princípios fundamentais do R</h4>
<p>A lógica do R pode ser compreendida a partir de três princípios básicos:</p>
<p><strong>Tudo é um objeto:</strong> números, textos, conjuntos de dados, gráficos e funções podem ser armazenados e manipulados como objetos.</p>
<p><strong>As operações são realizadas por funções:</strong> diferentes comandos e cálculos são processados por meio de funções.</p>
<p><strong>Integração com outros sistemas:</strong> o R pode interagir com linguagens e tecnologias como C, C++, Python, HTML e JavaScript.</p>
</section>
<section id="sintaxe-e-principais-comandos" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="sintaxe-e-principais-comandos"><span class="header-section-number">3.1.2</span> Sintaxe e principais comandos</h4>
<p>A sintaxe corresponde às regras utilizadas para escrever corretamente os comandos, enquanto a semântica está relacionada ao significado e ao resultado dessas instruções.</p>
<p>Ao iniciar o R ou o RStudio, o símbolo &gt; indica que o console está pronto para receber um comando. Quando uma instrução está incompleta, o símbolo + indica que o R aguarda sua continuação.</p>
<p>Os comentários são inseridos utilizando # e servem para documentar o código sem serem executados.</p>
<p>Os objetos devem receber nomes válidos, sem espaços ou operadores matemáticos. O R diferencia letras maiúsculas de minúsculas, de modo que idade e Idade representam objetos diferentes. Também é necessário evitar palavras reservadas da linguagem, como if, else, for e function.</p>
<p>As operações podem ser executadas diretamente ou armazenadas em objetos. Para atribuições, recomenda-se o uso do operador &lt;-</p>
<p>É possível ainda executar vários comandos na mesma linha utilizando ;</p>
</section>
</section>
<section id="gerenciamento-dos-objetos-e-do-diretório-de-trabalho." class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="gerenciamento-dos-objetos-e-do-diretório-de-trabalho."><span class="header-section-number">3.2</span> Gerenciamento dos objetos e do diretório de trabalho.</h3>
<p>Os objetos criados durante uma sessão ficam armazenados no ambiente de trabalho do R. O comando ls() permite visualizar os objetos existentes.</p>
<p>O diretório de trabalho pode ser consultado com getwd() e alterado utilizando setwd():</p>
<section id="tipos-de-dados-e-pacotes" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="tipos-de-dados-e-pacotes"><span class="header-section-number">3.2.1</span> Tipos de dados e pacotes</h4>
<p>O R trabalha com diferentes tipos básicos de dados, como logical, integer, double e character. Também possui estruturas mais complexas, como data frames, amplamente utilizadas para organizar dados em linhas e colunas. As funcionalidades do R podem ser ampliadas por meio de pacotes, que reúnem funções e outros recursos desenvolvidos para finalidades específicas. Para utilizar um pacote, normalmente é necessário instalá-lo e carregá-lo:</p>
<p>install.packages(“nome_do_pacote”) library(nome_do_pacote)</p>
<p>Também é possível utilizar diretamente uma função de determinado pacote por meio do operador :::</p>
<p>nome_do_pacote::nome_da_funcao(argumentos)</p>
<p>O domínio desses fundamentos permite compreender a estrutura básica do R, facilitando a criação, organização e execução de códigos e fornecendo uma base para atividades de tratamento, visualização e análise estatística de dados.</p>
</section>
</section>
<section id="conceitos-fundamentais-da-estatística" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="conceitos-fundamentais-da-estatística"><span class="header-section-number">3.3</span> Conceitos fundamentais da estatística</h3>
<section id="população-e-amostra" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="população-e-amostra"><span class="header-section-number">3.3.1</span> População e Amostra</h4>
<p>A população (<strong>N</strong>) corresponde ao conjunto de elementos que apresentam uma ou mais características de interesse para determinado estudo. Pode ser finita, quando seus elementos podem ser enumerados, ou infinita, quando isso não é possível.</p>
<p>A amostra (<strong>n</strong>)é uma parte da população selecionada para representar suas características. Quando todos os elementos da população são analisados, realiza-se um censo, não sendo necessária a utilização de procedimentos de inferência estatística. Apresente os conceitos principais:</p>
</section>
<section id="classificação-das-variaveis" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="classificação-das-variaveis"><span class="header-section-number">3.3.2</span> Classificação das variaveis</h4>
<p>As variáveis representam as características que serão observadas ou medidas em uma pesquisa. Podem ser classificadas em:</p>
<p><strong>Qualitativas:</strong> representam características ou categorias. Podem ser nominais, quando não possuem uma ordem natural, ou ordinais, quando apresentam uma hierarquia.</p>
<p><strong>Quantitativas:</strong> representam valores numéricos. São discretas quando resultam de contagens e contínuas quando resultam de medições e podem assumir diferentes valores em determinado intervalo.</p>
<p>É importante observar que números utilizados apenas como códigos ou identificadores não transformam uma variável qualitativa em quantitativa.</p>
</section>
</section>
<section id="notação-de-somatório" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="notação-de-somatório"><span class="header-section-number">3.4</span> Notação de Somatório</h3>
<p>A notação de somatório permite representar, de forma compacta, a soma de vários valores e é utilizada em diversas fórmulas estatísticas. O índice indica a posição das observações e o limite superior determina até onde a soma será realizada.</p>
<p><span class="math display">\[
\sum_{i=1}^{n} x_i = x_1+x_2+x_3+\cdots+x_n
\]</span></p>
<p>Uma distinção importante é entre o somatório dos quadrados e o quadrado do somatório. No primeiro caso, cada valor é elevado ao quadrado antes da soma; no segundo, os valores são somados e somente depois o resultado é elevado ao quadrado.</p>
<p>O somatório também apresenta propriedades algébricas que facilitam a manipulação das expressões estatísticas, como a possibilidade de retirar constantes do somatório e distribuir a operação sobre somas ou diferenças.</p>
<p>Uma propriedade importante é que a soma dos desvios em relação à média é igual a zero. Por isso, medidas de dispersão utilizam o módulo ou, principalmente, o quadrado dos desvios para evitar o cancelamento entre valores positivos e negativos.</p>
</section>
<section id="organização-dos-dados-e-distribuição-de-frequências" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="organização-dos-dados-e-distribuição-de-frequências"><span class="header-section-number">3.5</span> Organização dos dados e Distribuição de Frequências</h3>
<p>Os dados obtidos diretamente de uma pesquisa são denominados dados brutos. Antes da análise, é necessário organizá-los de forma adequada.</p>
<p>O rol consiste na ordenação dos dados, geralmente em ordem crescente ou decrescente. Essa organização facilita a identificação dos menores e maiores valores e é necessária para o cálculo de medidas como a mediana.</p>
<p>A frequência absoluta representa o número de vezes que determinado valor ou categoria ocorre. A frequência relativa expressa essa ocorrência em proporção ao total de observações, enquanto a frequência percentual apresenta o mesmo resultado em porcentagem.</p>
<p>As frequências acumuladas permitem identificar a quantidade de observações que se encontra abaixo ou acima de determinado valor ou classe.</p>
<p>Para variáveis contínuas, os dados podem ser agrupados em intervalos de classe, facilitando sua apresentação e interpretação. A construção das classes envolve a definição do número de classes, da amplitude total, da amplitude dos intervalos, dos limites e do ponto médio de cada classe. Após essa definição, são calculadas as respectivas frequências.</p>
</section>
<section id="medidas-de-posição" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="medidas-de-posição"><span class="header-section-number">3.6</span> Medidas de Posição</h3>
<p>As medidas de posição permitem representar um conjunto de dados por meio de um valor central ou representativo. As principais são média, mediana e moda.</p>
<section id="média-aritmética" class="level4" data-number="3.6.1">
<h4 data-number="3.6.1" class="anchored" data-anchor-id="média-aritmética"><span class="header-section-number">3.6.1</span> Média aritmética</h4>
<p>A média aritmética é obtida pela soma dos valores observados dividida pelo número de observações. É amplamente utilizada em análises estatísticas, principalmente quando os dados apresentam distribuição aproximadamente simétrica e não possuem valores discrepantes.</p>
<p><span class="math display">\[
\bar{x} = \frac{1}{n}\sum_{i=1}^{n}x_i
\]</span> Quando os dados estão organizados em uma tabela de frequências, a média pode ser calculada considerando a frequência de cada valor ou o ponto médio das classes.</p>
<p>A média também apresenta propriedades importantes: a adição ou subtração de uma constante altera seu valor na mesma proporção, enquanto a multiplicação ou divisão por uma constante modifica a média pelo mesmo fator.</p>
</section>
<section id="média-aparada" class="level4" data-number="3.6.2">
<h4 data-number="3.6.2" class="anchored" data-anchor-id="média-aparada"><span class="header-section-number">3.6.2</span> Média Aparada</h4>
<p>A média aparada é obtida após a retirada de uma determinada proporção dos maiores e menores valores. É uma alternativa à média tradicional quando existem valores extremos que podem influenciar significativamente o resultado. <span class="math display">\[
\bar{x}_{\text{aparada}}
=
\frac{1}{n-2k}
\sum_{i=k+1}^{n-k}x_{(i)}
\]</span></p>
</section>
<section id="mediana" class="level4" data-number="3.6.3">
<h4 data-number="3.6.3" class="anchored" data-anchor-id="mediana"><span class="header-section-number">3.6.3</span> Mediana</h4>
<p>A mediana corresponde ao valor que divide os dados ordenados em duas partes iguais, deixando aproximadamente 50% das observações abaixo e 50% acima. Por depender da posição dos valores, apresenta maior resistência à influência de valores extremos do que a média. <span class="math display">\[
Md = x_{\left(\frac{n+1}{2}\right)}
\]</span> Para dados agrupados em classes, a mediana é estimada por meio de interpolação dentro da classe que contém a posição central dos dados.</p>
</section>
<section id="moda" class="level4" data-number="3.6.4">
<h4 data-number="3.6.4" class="anchored" data-anchor-id="moda"><span class="header-section-number">3.6.4</span> Moda</h4>
<p>A moda corresponde ao valor ou categoria que apresenta maior frequência. Uma distribuição pode ser unimodal, quando possui uma única moda, ou apresentar duas ou mais modas.</p>
<p>Quando os dados estão agrupados em classes, a moda pode ser estimada a partir da classe modal, utilizando métodos específicos, como a fórmula de Czuber.</p>
<p>A relação empírica de Pearson também pode ser utilizada para estimar a moda a partir da média e da mediana em distribuições unimodais com assimetria moderada.</p>
</section>
</section>
<section id="medidas-de-dispersão" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="medidas-de-dispersão"><span class="header-section-number">3.7</span> Medidas de dispersão</h3>
<p>As medidas de dispersão indicam o grau de variabilidade existente nos dados. Essa informação é importante porque conjuntos de dados podem apresentar médias semelhantes, mas diferentes níveis de dispersão.</p>
<section id="amplitude-total" class="level4" data-number="3.7.1">
<h4 data-number="3.7.1" class="anchored" data-anchor-id="amplitude-total"><span class="header-section-number">3.7.1</span> Amplitude total</h4>
<p>A amplitude total corresponde à diferença entre o maior e o menor valor observado. É uma medida simples e rápida, porém bastante influenciada por valores extremos. <span class="math display">\[
AT = x_{\max} - x_{\min}
\]</span></p>
</section>
<section id="soma-de-quadrados" class="level4" data-number="3.7.2">
<h4 data-number="3.7.2" class="anchored" data-anchor-id="soma-de-quadrados"><span class="header-section-number">3.7.2</span> Soma de quadrados</h4>
<p>A soma de quadrados representa a soma dos desvios quadráticos das observações em relação ao centro dos dados. Constitui uma etapa importante para o cálculo da variância e de outros procedimentos estatísticos. <span class="math display">\[
SQ = \sum_{i=1}^{n}(x_i-\bar{x})^2
\]</span></p>
</section>
<section id="variância" class="level4" data-number="3.7.3">
<h4 data-number="3.7.3" class="anchored" data-anchor-id="variância"><span class="header-section-number">3.7.3</span> Variância</h4>
<p>A variância mede a dispersão dos valores em relação à média. No caso de amostras, utiliza-se a correção pelos graus de liberdade, com divisão por n - 1, buscando obter um estimador não viesado da variância populacional. <span class="math display">\[
s^2 = \frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}
\]</span> Para dados agrupados, a variância pode ser calculada considerando as frequências e os pontos médios das classes.</p>
</section>
<section id="desvio-padrão" class="level4" data-number="3.7.4">
<h4 data-number="3.7.4" class="anchored" data-anchor-id="desvio-padrão"><span class="header-section-number">3.7.4</span> Desvio padrão</h4>
<p>O desvio padrão corresponde à raiz quadrada da variância e apresenta a vantagem de estar expresso na mesma unidade dos dados originais. Por isso, é uma das principais medidas de dispersão utilizadas em análises estatísticas e relatórios técnicos. <span class="math display">\[
s = \sqrt{\frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}}
\]</span> A adição ou subtração de uma constante aos dados não altera o desvio padrão. Já a multiplicação dos dados por uma constante altera o desvio padrão proporcionalmente e a variância pelo quadrado dessa constante.</p>
</section>
<section id="coeficiente-de-variação" class="level4" data-number="3.7.5">
<h4 data-number="3.7.5" class="anchored" data-anchor-id="coeficiente-de-variação"><span class="header-section-number">3.7.5</span> Coeficiente de variação</h4>
<p>O coeficiente de variação representa a dispersão de forma relativa à média, permitindo comparar a variabilidade entre conjuntos de dados com diferentes escalas ou magnitudes. Valores menores indicam, em geral, maior homogeneidade dos dados. <span class="math display">\[
CV = \frac{s}{\bar{x}}\times100
\]</span> Sua utilização deve ser feita com cautela, especialmente quando a média apresenta valores próximos de zero ou quando a variável não possui um zero absoluto significativo.</p>
</section>
<section id="erro-padrão-da-média" class="level4" data-number="3.7.6">
<h4 data-number="3.7.6" class="anchored" data-anchor-id="erro-padrão-da-média"><span class="header-section-number">3.7.6</span> Erro padrão da média</h4>
<p>O erro padrão da média representa a variabilidade esperada da média amostral em relação à média da população. Seu valor diminui à medida que o tamanho da amostra aumenta, indicando que amostras maiores tendem a produzir estimativas mais estáveis. <span class="math display">\[
EP = \frac{s}{\sqrt{n}}
\]</span> Essa medida é utilizada em procedimentos de inferência estatística, incluindo intervalos de confiança e testes de hipóteses.</p>
</section>
</section>
<section id="tópico-adicional-medidas-de-forma-assimetria-e-curtose" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="tópico-adicional-medidas-de-forma-assimetria-e-curtose"><span class="header-section-number">3.8</span> Tópico Adicional: Medidas de Forma (Assimetria e Curtose)</h3>
<p>Além do centro e do espalhamento, a estatística analisa a “silhueta” da distribuição geométrica dos dados.</p>
<section id="assimetria" class="level4" data-number="3.8.1">
<h4 data-number="3.8.1" class="anchored" data-anchor-id="assimetria"><span class="header-section-number">3.8.1</span> Assimetria</h4>
<p>Avalia o grau de distorção ou inclinação da curva de dados em relação a uma distribuição normal e perfeitamente simétrica. Utilizando o cálculo pelo 3º momento central, penaliza os desvios mantendo seus sinais positivos ou negativos: <span class="math display">\[ g_1 = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^3}{\left[\sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^2}\right]^3} \]</span> - <span class="math inline">\(g_1 = 0\)</span>: Distribuição simétrica (média <span class="math inline">\(\approx\)</span> mediana).<br> - <span class="math inline">\(g_1 &gt; 0\)</span>: Assimetria Positiva (cauda alongada para a direita, repuxada por valores altos).<br> - <span class="math inline">\(g_1 &lt; 0\)</span>: Assimetria Negativa (cauda alongada para a esquerda, influenciada por valores baixos).</p>
</section>
<section id="curtose" class="level4" data-number="3.8.2">
<h4 data-number="3.8.2" class="anchored" data-anchor-id="curtose"><span class="header-section-number">3.8.2</span> Curtose</h4>
<p>Mede o grau de achatamento da distribuição e a espessura de suas caudas (frequência de valores extremos). O cálculo padrão subtrai o valor 3, padronizando a distribuição normal no zero: <span class="math display">\[ g_2 = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^4}{\left[\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^2\right]^2} - 3 \]</span> - <span class="math inline">\(g_2 = 0\)</span> (Mesocúrtica): Curva com espalhamento similar à normal.<br> - <span class="math inline">\(g_2 &gt; 0\)</span> (Leptocúrtica): Curva mais afunilada, com pico elevado e caudas “pesadas” (alta chance de outliers).<br> - <span class="math inline">\(g_2 &lt; 0\)</span> (Platicúrtica): Curva achatada, indicando dados amplamente dispersos próximos ao centro.</p>
</section>
</section>
</section>
<section id="metodologia-e-estudo-de-caso" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="metodologia-e-estudo-de-caso"><span class="header-section-number">4</span> ⚙️ Metodologia e Estudo de Caso</h2>
<p>Foi utilizado o pacote computacional <code>leem</code> para os cálculos estatísticos, bem como para o agrupamento de classes, somatório de desvios e obtenção dos momentos centrais.</p>
<p><strong>Contexto do Estudo de Caso:</strong> Na construção de barragens e aterros estruturais, o <strong>Grau de Compactação (GC)</strong> é a principal variável tecnológica que atesta a segurança do maciço contra deformações e infiltrações. O GC é a razão percentual entre a massa específica seca alcançada no campo e a massa específica seca máxima obtida no ensaio de Proctor em laboratório <span class="citation" data-cites="abnt_nbr7182">(<a href="#ref-abnt_nbr7182" role="doc-biblioref">ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS, 2016</a>)</span>.</p>
<ul>
<li><strong>Parâmetro de Projeto:</strong> Conforme preconizado em norma, o ensaio de compactação deve resultar em, pelo menos, <strong><span class="math inline">\(GC \ge 95\%\)</span></strong> para garantir uma compactação eficiente e adequada <span class="citation" data-cites="abnt_nbr7182">(<a href="#ref-abnt_nbr7182" role="doc-biblioref">ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS, 2016</a>)</span>.</li>
<li><strong>Banco de Dados:</strong> Foi coletado <strong>50 resultados de ensaios</strong> realizados ao longo de uma camada do maciço terroso.</li>
</ul>
<p>A seguir, importaremos os dados no RStudio, realizaremos a tabulação em frequências (Cap. 2), calcularemos a posição e dispersão (Caps. 3 e 4) e interpretaremos a forma (Assimetria e Curtose) para emitir um diagnóstico de engenharia sobre a liberação ou rejeição deste aterro.</p>
<section id="inicialização-e-entrada-dos-dados" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="inicialização-e-entrada-dos-dados"><span class="header-section-number">4.1</span> Inicialização e Entrada dos Dados</h3>
<p>No ambiente profissional, grandes volumes de informações não são inseridos manualmente no código, mas importados de planilhas e bases de dados externas. Para este estudo de caso, os 50 resultados dos ensaios de campo foram previamente tabulados e armazenados em um arquivo com extensão <code>.csv</code> (valores separados por vírgula). O primeiro passo da análise consiste em utilizar o R para ler esse arquivo externo, extrair a coluna de interesse e transformar os dados em um objeto reconhecido pelo pacote estatístico.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregamento das bibliotecas de análise e formatação</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leem)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Importação dos dados a partir do arquivo CSV</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>tabela_importada <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dados_compactacao.csv"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Extração da coluna de dados como um vetor numérico</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>grau_compactacao <span class="ot">&lt;-</span> tabela_importada<span class="sc">$</span>Compactacao</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilização da função new_leem para classificar como variável contínua (2)</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>gc_leem <span class="ot">&lt;-</span> <span class="fu">new_leem</span>(grau_compactacao, <span class="at">variable =</span> <span class="dv">2</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorganizando os 50 dados em 5 colunas de 10 linhas para exibição compacta</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>tabela_exibicao <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">matrix</span>(grau_compactacao, <span class="at">ncol =</span> <span class="dv">5</span>, <span class="at">byrow =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibindo os dados brutos de forma formatada com a função kable</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabela_exibicao, </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="st">"c"</span>, </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Ensaios 1 a 10"</span>, <span class="st">"Ensaios 11 a 20"</span>, <span class="st">"Ensaios 21 a 30"</span>, <span class="st">"Ensaios 31 a 40"</span>, <span class="st">"Ensaios 41 a 50"</span>),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Base de Dados Importada - Grau de Compactação (%)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Base de Dados Importada - Grau de Compactação (%)</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Ensaios 1 a 10</th>
<th style="text-align: center;">Ensaios 11 a 20</th>
<th style="text-align: center;">Ensaios 21 a 30</th>
<th style="text-align: center;">Ensaios 31 a 40</th>
<th style="text-align: center;">Ensaios 41 a 50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">95.2</td>
<td style="text-align: center;">97.1</td>
<td style="text-align: center;">95.9</td>
<td style="text-align: center;">98.7</td>
<td style="text-align: center;">96.9</td>
</tr>
<tr class="even">
<td style="text-align: center;">98.1</td>
<td style="text-align: center;">96.4</td>
<td style="text-align: center;">99.6</td>
<td style="text-align: center;">95.4</td>
<td style="text-align: center;">97.7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">94.5</td>
<td style="text-align: center;">98.9</td>
<td style="text-align: center;">96.8</td>
<td style="text-align: center;">99.8</td>
<td style="text-align: center;">95.3</td>
</tr>
<tr class="even">
<td style="text-align: center;">99.3</td>
<td style="text-align: center;">95.5</td>
<td style="text-align: center;">97.6</td>
<td style="text-align: center;">97.9</td>
<td style="text-align: center;">98.3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">96.7</td>
<td style="text-align: center;">99.1</td>
<td style="text-align: center;">95.1</td>
<td style="text-align: center;">96.1</td>
<td style="text-align: center;">100.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">97.5</td>
<td style="text-align: center;">97.8</td>
<td style="text-align: center;">98.2</td>
<td style="text-align: center;">94.7</td>
<td style="text-align: center;">94.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">95.8</td>
<td style="text-align: center;">96.2</td>
<td style="text-align: center;">101.1</td>
<td style="text-align: center;">98.6</td>
<td style="text-align: center;">97.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">98.4</td>
<td style="text-align: center;">94.8</td>
<td style="text-align: center;">94.2</td>
<td style="text-align: center;">97.2</td>
<td style="text-align: center;">96.6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100.2</td>
<td style="text-align: center;">98.5</td>
<td style="text-align: center;">97.4</td>
<td style="text-align: center;">95.7</td>
<td style="text-align: center;">98.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">93.9</td>
<td style="text-align: center;">97.3</td>
<td style="text-align: center;">96.5</td>
<td style="text-align: center;">100.5</td>
<td style="text-align: center;">95.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="tabulação-de-frequências-consciência-do-processo" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="tabulação-de-frequências-consciência-do-processo"><span class="header-section-number">4.2</span> Tabulação de Frequências (Consciência do Processo)</h3>
<p>Ao executar a função <code>tabfreq()</code>, o algoritmo busca o valor mínimo (93.9%) e o máximo (101.1%), define a Amplitude Total da amostra e utiliza equações empíricas (como a regra de Sturges <span class="math inline">\(k \approx 1 + 3,322 \log n\)</span>) para encontrar um número ideal de classes de intervalo. Com as classes definidas, o algoritmo executa somatórios condicionais, contando quantas amostras caem dentro de cada intervalo.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Geração e plotagem nativa da tabela de distribuição de frequências</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>tabela_gc <span class="ot">&lt;-</span> <span class="fu">tabfreq</span>(gc_leem)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabela_gc<span class="sc">$</span>table, <span class="at">align =</span> <span class="st">"c"</span>, <span class="at">caption =</span> <span class="st">"Tabela de Distribuição de Frequência - GC (%)"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabela de Distribuição de Frequência - GC (%)</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Classes</th>
<th style="text-align: center;">Fi</th>
<th style="text-align: center;">PM</th>
<th style="text-align: center;">Fr</th>
<th style="text-align: center;">Fac1</th>
<th style="text-align: center;">Fac2</th>
<th style="text-align: center;">Fp</th>
<th style="text-align: center;">Fac1p</th>
<th style="text-align: center;">Fac2p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">93.3 |— 94.5</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">93.9</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td style="text-align: center;">94.5 |— 95.7</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">95.1</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">94</td>
</tr>
<tr class="odd">
<td style="text-align: center;">95.7 |— 96.9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">96.3</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">76</td>
</tr>
<tr class="even">
<td style="text-align: center;">96.9 |— 98.1</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">97.5</td>
<td style="text-align: center;">0.22</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">66</td>
<td style="text-align: center;">56</td>
</tr>
<tr class="odd">
<td style="text-align: center;">98.1 |— 99.3</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">98.7</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">86</td>
<td style="text-align: center;">34</td>
</tr>
<tr class="even">
<td style="text-align: center;">99.3 |— 100.5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">99.9</td>
<td style="text-align: center;">0.08</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">94</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100.5 |— 101.7</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">101.1</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A tabulação já nos adianta o primeiro alerta: embora a maior densidade dos dados (<span class="math inline">\(F_i\)</span>) esteja bem alocada nas faixas superiores a 95%, existe uma parcela de ensaios que caiu nas classes mais baixas do conjunto.</p>
</section>
<section id="síntese-descritiva-posição-dispersão-e-forma" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="síntese-descritiva-posição-dispersão-e-forma"><span class="header-section-number">4.3</span> Síntese Descritiva: Posição, Dispersão e Forma</h3>
<p>Para validar o maciço, não basta olhar para a tabela. Precisamos quantificar matematicamente o comportamento através dos momentos estatísticos. O código abaixo automatiza as equações dos Capítulos 3 e 4.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Medidas de Posição</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>gc_media <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">mean</span>(grau_compactacao))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>gc_mediana <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">median</span>(grau_compactacao))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Medidas de Dispersão</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>gc_desvio <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">sd</span>(grau_compactacao))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>gc_var <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">var</span>(grau_compactacao))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>gc_cv <span class="ot">&lt;-</span> (gc_desvio <span class="sc">/</span> gc_media) <span class="sc">*</span> <span class="dv">100</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Medidas de Forma (Cálculo via Momentos Centrais)</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>n_amostras <span class="ot">&lt;-</span> <span class="fu">length</span>(grau_compactacao)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Somatório (xi - x_barra)^3</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>momento3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n_amostras</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>desvio_cubico <span class="ot">&lt;-</span> (<span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n_amostras)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>gc_assimetria <span class="ot">&lt;-</span> momento3 <span class="sc">/</span> desvio_cubico</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Somatório (xi - x_barra)^4</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>momento4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n_amostras</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>desvio_quarto <span class="ot">&lt;-</span> (<span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n_amostras)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>gc_curtose <span class="ot">&lt;-</span> (momento4 <span class="sc">/</span> desvio_quarto) <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Consolidação dos Resultados</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>estatisticas_gc <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  Parâmetro <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Média (%)"</span>, <span class="st">"Mediana (%)"</span>, <span class="st">"Desvio Padrão (%)"</span>, </span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Variância (%²)"</span>, <span class="st">"CV (%)"</span>, <span class="st">"Assimetria"</span>, <span class="st">"Curtose"</span>),</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">round</span>(<span class="fu">c</span>(gc_media, gc_mediana, gc_desvio, </span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>                      gc_var, gc_cv, gc_assimetria, gc_curtose), <span class="dv">3</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(estatisticas_gc, <span class="at">align =</span> <span class="st">"c"</span>, <span class="at">caption =</span> <span class="st">"Estatísticas Descritivas Consolidadas - GC"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estatísticas Descritivas Consolidadas - GC</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Parâmetro</th>
<th style="text-align: center;">Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Média (%)</td>
<td style="text-align: center;">97.186</td>
</tr>
<tr class="even">
<td style="text-align: center;">Mediana (%)</td>
<td style="text-align: center;">97.150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Desvio Padrão (%)</td>
<td style="text-align: center;">1.838</td>
</tr>
<tr class="even">
<td style="text-align: center;">Variância (%²)</td>
<td style="text-align: center;">3.377</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CV (%)</td>
<td style="text-align: center;">1.891</td>
</tr>
<tr class="even">
<td style="text-align: center;">Assimetria</td>
<td style="text-align: center;">0.178</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Curtose</td>
<td style="text-align: center;">-0.714</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Análise Crítica dos Resultados:</strong></p>
<ul>
<li><strong>Centro Equilibrado:</strong> O algoritmo obteve uma média de <strong>97,14%</strong> e mediana de <strong>97,15%</strong>. A proximidade quase exata dessas duas grandezas confirma que não há “puxões” fortes (outliers severos) dominando o centro dos dados.</li>
<li><strong>Homogeneidade de Execução:</strong> O Coeficiente de Variação (CV) foi extremamente baixo (<strong>1,86%</strong>). Tal valor atesta que a frota de maquinário (rolos compactadores, caminhões-pipa e motoniveladoras) executou o serviço com padrão uniforme de energia em quase toda a praça de trabalho.</li>
<li><strong>Diagnóstico de Forma:</strong>
<ul>
<li>A <strong>Assimetria levemente positiva (0,157)</strong> indica uma distribuição quase simétrica, mas com uma ínfima tendência de cauda para a direita (algumas amostras com compactação excepcional puxando levemente a curva).</li>
<li>A <strong>Curtose negativa (-0,735)</strong> revela uma distribuição platicúrtica. Ou seja, em vez de se concentrar aguda e perigosamente no centro, os dados estão distribuídos de forma mais constante, com caudas mais curtas, o que estatisticamente diminui a chance da ocorrência de desvios drásticos e isolados.</li>
</ul></li>
</ul>
</section>
<section id="apresentação-gráfica-e-decisão-de-engenharia" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="apresentação-gráfica-e-decisão-de-engenharia"><span class="header-section-number">4.4</span> Apresentação Gráfica e Decisão de Engenharia</h3>
<p><strong>Análise Gráfica de Dispersão e Outliers (Boxplot)</strong></p>
<p>Para validar visualmente as métricas de dispersão, assimetria e curtose calculadas anteriormente, a ferramenta estatística mais robusta é o <em>Boxplot</em> (Diagrama de Caixa). Ele segmenta os dados em quartis (blocos de 25% da amostra) e permite identificar imediatamente a presença de anomalias operacionais (<em>outliers</em>) e o achatamento da distribuição.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuração do Boxplot em R</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(grau_compactacao,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">horizontal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#d0e1f9"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"#1e3d59"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Grau de Compactação (%)"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot do Grau de Compactação"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Adicionando o Limite de Especificação para referência</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">95.0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="st">"Limite Mín (95%)"</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/grafico-boxplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>A linha escura que corta a caixa no meio representa a Mediana (97,15%). O fato de ela estar exatamente no centro do retângulo azul confirma uma <em>Assimetria quase nula</em>.</li>
<li>O tamanho estreito da caixa retangular (que concentra os 50% centrais de todos os ensaios) comprova visualmente o baixo Coeficiente de Variação (CV). O maquinário compactou quase todo o material dentro de uma faixa de energia muito previsível.</li>
<li>Os traços laterais (conhecidos como “bigodes”) indicam as caudas da distribuição. Como estão curtos e não vemos pequenos pontos isolados para fora deles, confirmamos a <em>Curtose negativa</em>, ou seja, uma distribuição achatada e sem outliers caindo fora do padrão esperado.</li>
</ul>
<p><strong>Distribuição dos Dados</strong></p>
<p>O histograma sobreposto pelos limites de aceitação possui a resposta para a aprovação ou reprovação da camada pelo engenheiro fiscal.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(grau_compactacao, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">7</span>, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#a8c0d8"</span>, </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"white"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Análise da Distribuição do GC"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Grau de Compactação alcançado (%)"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequência (Nº de Ensaios)"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Marcadores Críticos de Tomada de Decisão</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">95.0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># Limite Mínimo de Projeto</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> gc_media, <span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="co"># Desempenho Real</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Média Executada (97.1%)"</span>, <span class="st">"Limite Projeto - Mín 95%"</span>), </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"darkgreen"</span>, <span class="st">"red"</span>), </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/histograma-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>O Veredito do Estudo de Caso:</strong></p>
<p>As representações gráficas consolidam o diagnóstico operacional. O <em>Boxplot</em> atesta a homogeneidade geral do serviço, comprovando que não existem <em>outliers</em> decorrentes de falhas graves de execução. Contudo, o histograma evidencia que o limiar de projeto (95%) intercepta a cauda inferior da distribuição, afetando o primeiro bloco de frequências.</p>
<p>Observando o banco de dados e a área sob o gráfico, constata-se que, apesar do serviço excelente na média (Média &gt; 97% e CV baixíssimo), ocorreram <strong>6 ensaios reprovados</strong> (valores abaixo de 95%, perfazendo 12% da amostra). O engenheiro fiscal responsável não precisa rejeitar todo o lote, mas deve solicitar a <strong>recompactação setorial</strong> nos pontos específicos onde esses resultados foram obtidos. Essa intervenção é necessária para maximizar confiabilidade estrutural antes da liberação do aterro para a próxima camada.</p>
</section>
</section>
<section id="considerações-finais" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="considerações-finais"><span class="header-section-number">5</span> 🧠 Considerações Finais</h2>
<p>O presente relatório demonstrou a importância da Estatística Descritiva como ferramenta essencial para o controle de qualidade na Engenharia Civil. A revisão teórica embasou a aplicação computacional no RStudio com o pacote leem, comprovando que o uso de rotinas programadas otimiza o tratamento de dados e garante maior confiabilidade aos resultados, substituindo procedimentos manuais.</p>
<p>No estudo de caso sobre o Grau de Compactação, a aplicação integrada das medidas de posição, dispersão e forma foi determinante para a tomada de decisão. A análise restrita à média indicaria a aceitação total do serviço; porém, a avaliação da variância aliada ao histograma permitiu identificar desvios específicos, embasando a recomendação de correção pontual em 12% da área analisada. Assim, os objetivos da prática foram atingidos, evidenciando que o domínio conjunto de conceitos estatísticos e ferramentas computacionais é fundamental para análises técnicas mais seguras e criteriosas no canteiro de obras.</p>
</section>
<section id="referências" class="level2" data-number="6">

<!-- -->


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">6 📖 Referências</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-abnt_nbr7182" class="csl-entry" role="listitem">
ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS. <strong><span>ABNT NBR 7182</span>: Solo - Ensaio de compactação</strong>. Rio de Janeiro: ABNT, 2016.
</div>
<div id="ref-Rbasico2022" class="csl-entry" role="listitem">
BATISTA, B. D. O.; OLIVEIRA, D. A. B. J. <strong>R básico</strong>. 1. ed. Ouro Branco, MG: [s.n.], 2022. p. 321
</div>
<div id="ref-batista2024epaec" class="csl-entry" role="listitem">
OLIVEIRA BATISTA, B. D. DE. <strong>Estatística Básica aplicada às Engenharias e Ciências</strong>. Ouro Branco, MG: [s.n.], 2024.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Só mude aqui!!!!</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Marcus Fillipe e Gustavo"</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Relatório 01 - Fundamentos Iniciais da Linguagem R e Estatística Básica"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> referencias.bib</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># A partir daqui nao faca alteracoes!!!!!</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="an">link-citations:</span><span class="co"> true</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> associacao-brasileira-de-normas-tecnicas-ipea.csl</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "&lt;a href='https://bendeivide.github.io/courses/epaec/' target='_blank'&gt;Estatística e Probabilidade&lt;/a&gt; &lt;/br&gt; &lt;a href='https://bendeivide.github.io' target='_blank'&gt;Prof. Ben Dêivide (DEFIM/CAP/UFSJ)&lt;/a&gt;"</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="an">include-before-body:</span><span class="co"> header.html</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> now</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="an">date-format:</span><span class="co"> "DD/MM/YYYY, HH:mm"</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> pt-BR</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: bootstrap</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="co">    #css: styles.css</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📌 Introdução</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>  A utilização de métodos estatísticos é de grande importância para o tratamento e a interpretação de informações obtidas em diferentes áreas da Engenharia. Na Engenharia Civil, esses métodos podem ser empregados na avaliação de resultados experimentais, no controle de qualidade, em levantamentos técnicos e no estudo das propriedades e do comportamento de materiais. A análise dos dados permite identificar características, tendências e variações, fornecendo subsídios para uma interpretação mais adequada dos resultados e para a tomada de decisões.</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  A Estatística Descritiva permite organizar e apresentar os dados de forma simplificada, facilitando sua compreensão. Para isso, podem ser utilizadas tabelas e gráficos, além de medidas de posição e dispersão. Indicadores como assimetria e curtose também auxiliam na avaliação da distribuição dos dados. Dessa forma, é possível obter uma visão geral do conjunto analisado e identificar comportamentos que podem ser relevantes para o estudo.</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>  O desenvolvimento de ferramentas computacionais também contribui para tornar as análises estatísticas mais práticas e eficientes. Nesse contexto, a linguagem R apresenta diversos recursos destinados ao processamento e à análise de dados, enquanto o RStudio oferece um ambiente que facilita a elaboração e execução dos comandos, bem como a visualização dos resultados e gráficos. A utilização de pacotes específicos, como o leem, permite ampliar as funcionalidades disponíveis e auxiliar na realização dos procedimentos estatísticos.</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>  Diante disso, esta prática consiste na aplicação de conceitos de Estatística Descritiva utilizando a linguagem R, o ambiente RStudio e o pacote leem. Os procedimentos serão aplicados a dados relacionados à Engenharia Civil, envolvendo sua organização, representação e análise. A atividade busca, portanto, associar os conceitos estatísticos aos recursos computacionais, possibilitando uma interpretação mais clara e fundamentada dos resultados obtidos.</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🎯 Objetivos</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivo geral</span></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>Aplicar os fundamentos da Estatística Descritiva e da programação em R na análise de dados voltados à Engenharia Civil. A prática fundamenta-se nos quatro primeiros capítulos do livro *Estatística &amp; Probabilidade Aplicada às Engenharias e Ciências (EPAEC)* de @batista2024epaec, integrando a teoria matemática à execução computacional por meio do pacote <span class="in">`leem`</span>, visando a organização, representação e a discussão crítica de um estudo de caso prático.</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivos específicos</span></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Introduzir os conceitos de base da linguagem R e do RStudio (sintaxe, semântica e gerenciamento de objetos), fundamentados tanto no livro de @Rbasico2022, quanto nas 26 vídeo-aulas do curso R Básico.</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Revisar os conceitos iniciais da estatística (população, amostra e variáveis), além da notação de somatórios (Capítulo 1 do EPAEC).</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Aplicar técnicas de coleta, organização, tabulação e apresentação gráfica de dados quantitativos (Capítulo 2 do EPAEC).</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Compreender as formulações matemáticas e o significado prático das principais Medidas de Posição: média, mediana e moda (Capítulo 3 do EPAEC).</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Compreender e calcular as Medidas de Dispersão: amplitude, variância, desvio padrão, coeficiente de variação e erro padrão (Capítulo 4 do EPAEC).</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Pesquisar, definir e implementar o cálculo das Medidas de Forma (Assimetria e Curtose), interpretando o formato das distribuições estatísticas.</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Utilizar o pacote <span class="in">`leem`</span> para estruturar um banco de dados de Engenharia Civil (Controle de Compactação de Solos), gerando análises numéricas e gráficas exequíveis.</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Discutir o diagnóstico de engenharia gerado pelos dados, avaliando o atendimento a critérios de projeto e a qualidade de execução de um serviço hipotético.</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📚  Fundamentação Teórica</span></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fundamentos do R e do RStudio</span></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>O R é um ambiente computacional de código aberto destinado à manipulação e análise de dados, realização de cálculos estatísticos e produção de gráficos. Além de suas funções nativas, permite a criação e o compartilhamento de novas funcionalidades por meio de pacotes desenvolvidos pela comunidade.</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>O projeto foi iniciado em 1991, na Nova Zelândia, pelos pesquisadores Ross Ihaka e Robert Gentleman, tendo sua primeira versão oficial disponibilizada em 1995. Em 1997, foi criado o CRAN (Comprehensive R Archive Network), responsável pela distribuição do R, de sua documentação e de milhares de pacotes.</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>O RStudio é uma IDE (Integrated Development Environment) desenvolvida para facilitar a utilização do R. Ele não substitui o R, mas oferece uma interface organizada para escrita e execução de códigos. Sua estrutura reúne, principalmente, o editor de scripts, o console, o painel de ambiente e histórico e as áreas destinadas a arquivos, gráficos, pacotes e ajuda.</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Princípios fundamentais do R</span></span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>A lógica do R pode ser compreendida a partir de três princípios básicos:</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>**Tudo é um objeto:** números, textos, conjuntos de dados, gráficos e funções podem ser armazenados e manipulados como objetos.</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>**As operações são realizadas por funções:** diferentes comandos e cálculos são processados por meio de funções.</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>**Integração com outros sistemas:** o R pode interagir com linguagens e tecnologias como C, C++, Python, HTML e JavaScript.</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Sintaxe e principais comandos</span></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>A sintaxe corresponde às regras utilizadas para escrever corretamente os comandos, enquanto a semântica está relacionada ao significado e ao resultado dessas instruções.</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>Ao iniciar o R ou o RStudio, o símbolo &gt; indica que o console está pronto para receber um comando. Quando uma instrução está incompleta, o símbolo + indica que o R aguarda sua continuação.</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a>Os comentários são inseridos utilizando # e servem para documentar o código sem serem executados.</span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a>Os objetos devem receber nomes válidos, sem espaços ou operadores matemáticos. O R diferencia letras maiúsculas de minúsculas, de modo que idade e Idade representam objetos diferentes. Também é necessário evitar palavras reservadas da linguagem, como if, else, for e function.</span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a>As operações podem ser executadas diretamente ou armazenadas em objetos. Para atribuições, recomenda-se o uso do operador &lt;-</span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a>É possível ainda executar vários comandos na mesma linha utilizando ;</span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gerenciamento dos objetos e do diretório de trabalho.</span></span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a>Os objetos criados durante uma sessão ficam armazenados no ambiente de trabalho do R. O comando ls() permite visualizar os objetos existentes.</span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-90"><a href="#cb6-90" aria-hidden="true" tabindex="-1"></a>O diretório de trabalho pode ser consultado com getwd() e alterado utilizando setwd():</span>
<span id="cb6-91"><a href="#cb6-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-92"><a href="#cb6-92" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Tipos de dados e pacotes</span></span>
<span id="cb6-93"><a href="#cb6-93" aria-hidden="true" tabindex="-1"></a>O R trabalha com diferentes tipos básicos de dados, como logical, integer, double e character. Também possui estruturas mais complexas, como data frames, amplamente utilizadas para organizar dados em linhas e colunas.</span>
<span id="cb6-94"><a href="#cb6-94" aria-hidden="true" tabindex="-1"></a>As funcionalidades do R podem ser ampliadas por meio de pacotes, que reúnem funções e outros recursos desenvolvidos para finalidades específicas. Para utilizar um pacote, normalmente é necessário instalá-lo e carregá-lo:</span>
<span id="cb6-95"><a href="#cb6-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-96"><a href="#cb6-96" aria-hidden="true" tabindex="-1"></a>install.packages("nome_do_pacote")</span>
<span id="cb6-97"><a href="#cb6-97" aria-hidden="true" tabindex="-1"></a>library(nome_do_pacote)</span>
<span id="cb6-98"><a href="#cb6-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-99"><a href="#cb6-99" aria-hidden="true" tabindex="-1"></a>Também é possível utilizar diretamente uma função de determinado pacote por meio do operador :::</span>
<span id="cb6-100"><a href="#cb6-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-101"><a href="#cb6-101" aria-hidden="true" tabindex="-1"></a>nome_do_pacote::nome_da_funcao(argumentos)</span>
<span id="cb6-102"><a href="#cb6-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-103"><a href="#cb6-103" aria-hidden="true" tabindex="-1"></a>O domínio desses fundamentos permite compreender a estrutura básica do R, facilitando a criação, organização e execução de códigos e fornecendo uma base para atividades de tratamento, visualização e análise estatística de dados.</span>
<span id="cb6-104"><a href="#cb6-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-105"><a href="#cb6-105" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conceitos fundamentais da estatística </span></span>
<span id="cb6-106"><a href="#cb6-106" aria-hidden="true" tabindex="-1"></a><span class="fu">#### População e Amostra</span></span>
<span id="cb6-107"><a href="#cb6-107" aria-hidden="true" tabindex="-1"></a>A população (**N**) corresponde ao conjunto de elementos que apresentam uma ou mais características de interesse para determinado estudo. Pode ser finita, quando seus elementos podem ser enumerados, ou infinita, quando isso não é possível.</span>
<span id="cb6-108"><a href="#cb6-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-109"><a href="#cb6-109" aria-hidden="true" tabindex="-1"></a>A amostra (**n**)é uma parte da população selecionada para representar suas características. Quando todos os elementos da população são analisados, realiza-se um censo, não sendo necessária a utilização de procedimentos de inferência estatística.</span>
<span id="cb6-110"><a href="#cb6-110" aria-hidden="true" tabindex="-1"></a>Apresente os conceitos principais:</span>
<span id="cb6-111"><a href="#cb6-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-112"><a href="#cb6-112" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Classificação das variaveis</span></span>
<span id="cb6-113"><a href="#cb6-113" aria-hidden="true" tabindex="-1"></a>As variáveis representam as características que serão observadas ou medidas em uma pesquisa. Podem ser classificadas em:</span>
<span id="cb6-114"><a href="#cb6-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-115"><a href="#cb6-115" aria-hidden="true" tabindex="-1"></a>**Qualitativas:** representam características ou categorias. Podem ser nominais, quando não possuem uma ordem natural, ou ordinais, quando apresentam uma hierarquia.</span>
<span id="cb6-116"><a href="#cb6-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-117"><a href="#cb6-117" aria-hidden="true" tabindex="-1"></a>**Quantitativas:** representam valores numéricos. São discretas quando resultam de contagens e contínuas quando resultam de medições e podem assumir diferentes valores em determinado intervalo.</span>
<span id="cb6-118"><a href="#cb6-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-119"><a href="#cb6-119" aria-hidden="true" tabindex="-1"></a>É importante observar que números utilizados apenas como códigos ou identificadores não transformam uma variável qualitativa em quantitativa.</span>
<span id="cb6-120"><a href="#cb6-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-121"><a href="#cb6-121" aria-hidden="true" tabindex="-1"></a><span class="fu">### Notação de Somatório</span></span>
<span id="cb6-122"><a href="#cb6-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-123"><a href="#cb6-123" aria-hidden="true" tabindex="-1"></a>A notação de somatório permite representar, de forma compacta, a soma de vários valores e é utilizada em diversas fórmulas estatísticas. O índice indica a posição das observações e o limite superior determina até onde a soma será realizada.</span>
<span id="cb6-124"><a href="#cb6-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-125"><a href="#cb6-125" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-126"><a href="#cb6-126" aria-hidden="true" tabindex="-1"></a>\sum_{i=1}^{n} x_i = x_1+x_2+x_3+\cdots+x_n</span>
<span id="cb6-127"><a href="#cb6-127" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-128"><a href="#cb6-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-129"><a href="#cb6-129" aria-hidden="true" tabindex="-1"></a>Uma distinção importante é entre o somatório dos quadrados e o quadrado do somatório. No primeiro caso, cada valor é elevado ao quadrado antes da soma; no segundo, os valores são somados e somente depois o resultado é elevado ao quadrado.</span>
<span id="cb6-130"><a href="#cb6-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-131"><a href="#cb6-131" aria-hidden="true" tabindex="-1"></a>O somatório também apresenta propriedades algébricas que facilitam a manipulação das expressões estatísticas, como a possibilidade de retirar constantes do somatório e distribuir a operação sobre somas ou diferenças.</span>
<span id="cb6-132"><a href="#cb6-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-133"><a href="#cb6-133" aria-hidden="true" tabindex="-1"></a>Uma propriedade importante é que a soma dos desvios em relação à média é igual a zero. Por isso, medidas de dispersão utilizam o módulo ou, principalmente, o quadrado dos desvios para evitar o cancelamento entre valores positivos e negativos.</span>
<span id="cb6-134"><a href="#cb6-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-135"><a href="#cb6-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-136"><a href="#cb6-136" aria-hidden="true" tabindex="-1"></a><span class="fu">### Organização dos dados e Distribuição de Frequências</span></span>
<span id="cb6-137"><a href="#cb6-137" aria-hidden="true" tabindex="-1"></a>Os dados obtidos diretamente de uma pesquisa são denominados dados brutos. Antes da análise, é necessário organizá-los de forma adequada.</span>
<span id="cb6-138"><a href="#cb6-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-139"><a href="#cb6-139" aria-hidden="true" tabindex="-1"></a>O rol consiste na ordenação dos dados, geralmente em ordem crescente ou decrescente. Essa organização facilita a identificação dos menores e maiores valores e é necessária para o cálculo de medidas como a mediana.</span>
<span id="cb6-140"><a href="#cb6-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-141"><a href="#cb6-141" aria-hidden="true" tabindex="-1"></a>A frequência absoluta representa o número de vezes que determinado valor ou categoria ocorre. A frequência relativa expressa essa ocorrência em proporção ao total de observações, enquanto a frequência percentual apresenta o mesmo resultado em porcentagem.</span>
<span id="cb6-142"><a href="#cb6-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-143"><a href="#cb6-143" aria-hidden="true" tabindex="-1"></a>As frequências acumuladas permitem identificar a quantidade de observações que se encontra abaixo ou acima de determinado valor ou classe.</span>
<span id="cb6-144"><a href="#cb6-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-145"><a href="#cb6-145" aria-hidden="true" tabindex="-1"></a>Para variáveis contínuas, os dados podem ser agrupados em intervalos de classe, facilitando sua apresentação e interpretação. A construção das classes envolve a definição do número de classes, da amplitude total, da amplitude dos intervalos, dos limites e do ponto médio de cada classe. Após essa definição, são calculadas as respectivas frequências.</span>
<span id="cb6-146"><a href="#cb6-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-147"><a href="#cb6-147" aria-hidden="true" tabindex="-1"></a><span class="fu">### Medidas de Posição</span></span>
<span id="cb6-148"><a href="#cb6-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-149"><a href="#cb6-149" aria-hidden="true" tabindex="-1"></a>As medidas de posição permitem representar um conjunto de dados por meio de um valor central ou representativo. As principais são média, mediana e moda.</span>
<span id="cb6-150"><a href="#cb6-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-151"><a href="#cb6-151" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Média aritmética</span></span>
<span id="cb6-152"><a href="#cb6-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-153"><a href="#cb6-153" aria-hidden="true" tabindex="-1"></a>A média aritmética é obtida pela soma dos valores observados dividida pelo número de observações. É amplamente utilizada em análises estatísticas, principalmente quando os dados apresentam distribuição aproximadamente simétrica e não possuem valores discrepantes.</span>
<span id="cb6-154"><a href="#cb6-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-155"><a href="#cb6-155" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-156"><a href="#cb6-156" aria-hidden="true" tabindex="-1"></a>\bar{x} = \frac{1}{n}\sum_{i=1}^{n}x_i</span>
<span id="cb6-157"><a href="#cb6-157" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-158"><a href="#cb6-158" aria-hidden="true" tabindex="-1"></a>Quando os dados estão organizados em uma tabela de frequências, a média pode ser calculada considerando a frequência de cada valor ou o ponto médio das classes.</span>
<span id="cb6-159"><a href="#cb6-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-160"><a href="#cb6-160" aria-hidden="true" tabindex="-1"></a>A média também apresenta propriedades importantes: a adição ou subtração de uma constante altera seu valor na mesma proporção, enquanto a multiplicação ou divisão por uma constante modifica a média pelo mesmo fator.</span>
<span id="cb6-161"><a href="#cb6-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-162"><a href="#cb6-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-163"><a href="#cb6-163" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Média Aparada</span></span>
<span id="cb6-164"><a href="#cb6-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-165"><a href="#cb6-165" aria-hidden="true" tabindex="-1"></a>A média aparada é obtida após a retirada de uma determinada proporção dos maiores e menores valores. É uma alternativa à média tradicional quando existem valores extremos que podem influenciar significativamente o resultado.</span>
<span id="cb6-166"><a href="#cb6-166" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-167"><a href="#cb6-167" aria-hidden="true" tabindex="-1"></a>\bar{x}_{\text{aparada}}</span>
<span id="cb6-168"><a href="#cb6-168" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb6-169"><a href="#cb6-169" aria-hidden="true" tabindex="-1"></a>\frac{1}{n-2k}</span>
<span id="cb6-170"><a href="#cb6-170" aria-hidden="true" tabindex="-1"></a>\sum_{i=k+1}^{n-k}x_{(i)}</span>
<span id="cb6-171"><a href="#cb6-171" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-172"><a href="#cb6-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-173"><a href="#cb6-173" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Mediana</span></span>
<span id="cb6-174"><a href="#cb6-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-175"><a href="#cb6-175" aria-hidden="true" tabindex="-1"></a>A mediana corresponde ao valor que divide os dados ordenados em duas partes iguais, deixando aproximadamente 50% das observações abaixo e 50% acima. Por depender da posição dos valores, apresenta maior resistência à influência de valores extremos do que a média.</span>
<span id="cb6-176"><a href="#cb6-176" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-177"><a href="#cb6-177" aria-hidden="true" tabindex="-1"></a>Md = x_{\left(\frac{n+1}{2}\right)}</span>
<span id="cb6-178"><a href="#cb6-178" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-179"><a href="#cb6-179" aria-hidden="true" tabindex="-1"></a>Para dados agrupados em classes, a mediana é estimada por meio de interpolação dentro da classe que contém a posição central dos dados.</span>
<span id="cb6-180"><a href="#cb6-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-181"><a href="#cb6-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-182"><a href="#cb6-182" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Moda</span></span>
<span id="cb6-183"><a href="#cb6-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-184"><a href="#cb6-184" aria-hidden="true" tabindex="-1"></a>A moda corresponde ao valor ou categoria que apresenta maior frequência. Uma distribuição pode ser unimodal, quando possui uma única moda, ou apresentar duas ou mais modas.</span>
<span id="cb6-185"><a href="#cb6-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-186"><a href="#cb6-186" aria-hidden="true" tabindex="-1"></a>Quando os dados estão agrupados em classes, a moda pode ser estimada a partir da classe modal, utilizando métodos específicos, como a fórmula de Czuber.</span>
<span id="cb6-187"><a href="#cb6-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-188"><a href="#cb6-188" aria-hidden="true" tabindex="-1"></a>A relação empírica de Pearson também pode ser utilizada para estimar a moda a partir da média e da mediana em distribuições unimodais com assimetria moderada.</span>
<span id="cb6-189"><a href="#cb6-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-190"><a href="#cb6-190" aria-hidden="true" tabindex="-1"></a><span class="fu">### Medidas de dispersão</span></span>
<span id="cb6-191"><a href="#cb6-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-192"><a href="#cb6-192" aria-hidden="true" tabindex="-1"></a>As medidas de dispersão indicam o grau de variabilidade existente nos dados. Essa informação é importante porque conjuntos de dados podem apresentar médias semelhantes, mas diferentes níveis de dispersão.</span>
<span id="cb6-193"><a href="#cb6-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-194"><a href="#cb6-194" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Amplitude total</span></span>
<span id="cb6-195"><a href="#cb6-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-196"><a href="#cb6-196" aria-hidden="true" tabindex="-1"></a>A amplitude total corresponde à diferença entre o maior e o menor valor observado. É uma medida simples e rápida, porém bastante influenciada por valores extremos.</span>
<span id="cb6-197"><a href="#cb6-197" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-198"><a href="#cb6-198" aria-hidden="true" tabindex="-1"></a>AT = x_{\max} - x_{\min}</span>
<span id="cb6-199"><a href="#cb6-199" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-200"><a href="#cb6-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-201"><a href="#cb6-201" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Soma de quadrados</span></span>
<span id="cb6-202"><a href="#cb6-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-203"><a href="#cb6-203" aria-hidden="true" tabindex="-1"></a>A soma de quadrados representa a soma dos desvios quadráticos das observações em relação ao centro dos dados. Constitui uma etapa importante para o cálculo da variância e de outros procedimentos estatísticos.</span>
<span id="cb6-204"><a href="#cb6-204" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-205"><a href="#cb6-205" aria-hidden="true" tabindex="-1"></a>SQ = \sum_{i=1}^{n}(x_i-\bar{x})^2</span>
<span id="cb6-206"><a href="#cb6-206" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-207"><a href="#cb6-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-208"><a href="#cb6-208" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Variância</span></span>
<span id="cb6-209"><a href="#cb6-209" aria-hidden="true" tabindex="-1"></a>A variância mede a dispersão dos valores em relação à média. No caso de amostras, utiliza-se a correção pelos graus de liberdade, com divisão por n - 1, buscando obter um estimador não viesado da variância populacional.</span>
<span id="cb6-210"><a href="#cb6-210" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-211"><a href="#cb6-211" aria-hidden="true" tabindex="-1"></a>s^2 = \frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}</span>
<span id="cb6-212"><a href="#cb6-212" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-213"><a href="#cb6-213" aria-hidden="true" tabindex="-1"></a>Para dados agrupados, a variância pode ser calculada considerando as frequências e os pontos médios das classes.</span>
<span id="cb6-214"><a href="#cb6-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-215"><a href="#cb6-215" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Desvio padrão</span></span>
<span id="cb6-216"><a href="#cb6-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-217"><a href="#cb6-217" aria-hidden="true" tabindex="-1"></a>O desvio padrão corresponde à raiz quadrada da variância e apresenta a vantagem de estar expresso na mesma unidade dos dados originais. Por isso, é uma das principais medidas de dispersão utilizadas em análises estatísticas e relatórios técnicos.</span>
<span id="cb6-218"><a href="#cb6-218" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-219"><a href="#cb6-219" aria-hidden="true" tabindex="-1"></a>s = \sqrt{\frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}}</span>
<span id="cb6-220"><a href="#cb6-220" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-221"><a href="#cb6-221" aria-hidden="true" tabindex="-1"></a>A adição ou subtração de uma constante aos dados não altera o desvio padrão. Já a multiplicação dos dados por uma constante altera o desvio padrão proporcionalmente e a variância pelo quadrado dessa constante.</span>
<span id="cb6-222"><a href="#cb6-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-223"><a href="#cb6-223" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Coeficiente de variação</span></span>
<span id="cb6-224"><a href="#cb6-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-225"><a href="#cb6-225" aria-hidden="true" tabindex="-1"></a>O coeficiente de variação representa a dispersão de forma relativa à média, permitindo comparar a variabilidade entre conjuntos de dados com diferentes escalas ou magnitudes. Valores menores indicam, em geral, maior homogeneidade dos dados.</span>
<span id="cb6-226"><a href="#cb6-226" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-227"><a href="#cb6-227" aria-hidden="true" tabindex="-1"></a>CV = \frac{s}{\bar{x}}\times100</span>
<span id="cb6-228"><a href="#cb6-228" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-229"><a href="#cb6-229" aria-hidden="true" tabindex="-1"></a>Sua utilização deve ser feita com cautela, especialmente quando a média apresenta valores próximos de zero ou quando a variável não possui um zero absoluto significativo.</span>
<span id="cb6-230"><a href="#cb6-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-231"><a href="#cb6-231" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Erro padrão da média</span></span>
<span id="cb6-232"><a href="#cb6-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-233"><a href="#cb6-233" aria-hidden="true" tabindex="-1"></a>O erro padrão da média representa a variabilidade esperada da média amostral em relação à média da população. Seu valor diminui à medida que o tamanho da amostra aumenta, indicando que amostras maiores tendem a produzir estimativas mais estáveis.</span>
<span id="cb6-234"><a href="#cb6-234" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-235"><a href="#cb6-235" aria-hidden="true" tabindex="-1"></a>EP = \frac{s}{\sqrt{n}}</span>
<span id="cb6-236"><a href="#cb6-236" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-237"><a href="#cb6-237" aria-hidden="true" tabindex="-1"></a>Essa medida é utilizada em procedimentos de inferência estatística, incluindo intervalos de confiança e testes de hipóteses.</span>
<span id="cb6-238"><a href="#cb6-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-239"><a href="#cb6-239" aria-hidden="true" tabindex="-1"></a><span class="fu">### Tópico Adicional: Medidas de Forma (Assimetria e Curtose)</span></span>
<span id="cb6-240"><a href="#cb6-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-241"><a href="#cb6-241" aria-hidden="true" tabindex="-1"></a>Além do centro e do espalhamento, a estatística analisa a "silhueta" da distribuição geométrica dos dados.</span>
<span id="cb6-242"><a href="#cb6-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-243"><a href="#cb6-243" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Assimetria</span></span>
<span id="cb6-244"><a href="#cb6-244" aria-hidden="true" tabindex="-1"></a>Avalia o grau de distorção ou inclinação da curva de dados em relação a uma distribuição normal e perfeitamente simétrica. Utilizando o cálculo pelo 3º momento central, penaliza os desvios mantendo seus sinais positivos ou negativos:</span>
<span id="cb6-245"><a href="#cb6-245" aria-hidden="true" tabindex="-1"></a>$$ g_1 = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^3}{\left<span class="co">[</span><span class="ot">\sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^2}\right</span><span class="co">]</span>^3} $$</span>
<span id="cb6-246"><a href="#cb6-246" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$g_1 = 0$: Distribuição simétrica (média $\approx$ mediana).<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-247"><a href="#cb6-247" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$g_1 &gt; 0$: Assimetria Positiva (cauda alongada para a direita, repuxada por valores altos).<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-248"><a href="#cb6-248" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$g_1 &lt; 0$: Assimetria Negativa (cauda alongada para a esquerda, influenciada por valores baixos).</span>
<span id="cb6-249"><a href="#cb6-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-250"><a href="#cb6-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-251"><a href="#cb6-251" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Curtose</span></span>
<span id="cb6-252"><a href="#cb6-252" aria-hidden="true" tabindex="-1"></a>Mede o grau de achatamento da distribuição e a espessura de suas caudas (frequência de valores extremos). O cálculo padrão subtrai o valor 3, padronizando a distribuição normal no zero:</span>
<span id="cb6-253"><a href="#cb6-253" aria-hidden="true" tabindex="-1"></a>$$ g_2 = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^4}{\left<span class="co">[</span><span class="ot">\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^2\right</span><span class="co">]</span>^2} - 3 $$</span>
<span id="cb6-254"><a href="#cb6-254" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$g_2 = 0$ (Mesocúrtica): Curva com espalhamento similar à normal.<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-255"><a href="#cb6-255" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$g_2 &gt; 0$ (Leptocúrtica): Curva mais afunilada, com pico elevado e caudas "pesadas" (alta chance de outliers).<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb6-256"><a href="#cb6-256" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$g_2 &lt; 0$ (Platicúrtica): Curva achatada, indicando dados amplamente dispersos próximos ao centro.</span>
<span id="cb6-257"><a href="#cb6-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-258"><a href="#cb6-258" aria-hidden="true" tabindex="-1"></a><span class="fu">## ⚙️ Metodologia e Estudo de Caso</span></span>
<span id="cb6-259"><a href="#cb6-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-260"><a href="#cb6-260" aria-hidden="true" tabindex="-1"></a>Foi utilizado o pacote computacional <span class="in">`leem`</span> para os cálculos estatísticos, bem como para o agrupamento de classes, somatório de desvios e obtenção dos momentos centrais.</span>
<span id="cb6-261"><a href="#cb6-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-262"><a href="#cb6-262" aria-hidden="true" tabindex="-1"></a>**Contexto do Estudo de Caso:**</span>
<span id="cb6-263"><a href="#cb6-263" aria-hidden="true" tabindex="-1"></a>Na construção de barragens e aterros estruturais, o **Grau de Compactação (GC)** é a principal variável tecnológica que atesta a segurança do maciço contra deformações e infiltrações. </span>
<span id="cb6-264"><a href="#cb6-264" aria-hidden="true" tabindex="-1"></a>O GC é a razão percentual entre a massa específica seca alcançada no campo e a massa específica seca máxima obtida no ensaio de Proctor em laboratório <span class="co">[</span><span class="ot">@abnt_nbr7182</span><span class="co">]</span>.</span>
<span id="cb6-265"><a href="#cb6-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-266"><a href="#cb6-266" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Parâmetro de Projeto:** Conforme preconizado em norma, o ensaio de compactação deve resultar em, pelo menos, **$GC \ge 95\%$** para garantir uma compactação eficiente e adequada <span class="co">[</span><span class="ot">@abnt_nbr7182</span><span class="co">]</span>. </span>
<span id="cb6-267"><a href="#cb6-267" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Banco de Dados:** Foi coletado **50 resultados de ensaios** realizados ao longo de uma camada do maciço terroso.</span>
<span id="cb6-268"><a href="#cb6-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-269"><a href="#cb6-269" aria-hidden="true" tabindex="-1"></a>A seguir, importaremos os dados no RStudio, realizaremos a tabulação em frequências (Cap. 2), calcularemos a posição e dispersão (Caps. 3 e 4) e interpretaremos a forma (Assimetria e Curtose) para emitir um diagnóstico de engenharia sobre a liberação ou rejeição deste aterro.</span>
<span id="cb6-270"><a href="#cb6-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-271"><a href="#cb6-271" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inicialização e Entrada dos Dados</span></span>
<span id="cb6-272"><a href="#cb6-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-273"><a href="#cb6-273" aria-hidden="true" tabindex="-1"></a>No ambiente profissional, grandes volumes de informações não são inseridos manualmente no código, mas importados de planilhas e bases de dados externas. Para este estudo de caso, os 50 resultados dos ensaios de campo foram previamente tabulados e armazenados em um arquivo com extensão <span class="in">`.csv`</span> (valores separados por vírgula). O primeiro passo da análise consiste em utilizar o R para ler esse arquivo externo, extrair a coluna de interesse e transformar os dados em um objeto reconhecido pelo pacote estatístico.</span>
<span id="cb6-274"><a href="#cb6-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-277"><a href="#cb6-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-278"><a href="#cb6-278" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: preparacao-dados</span></span>
<span id="cb6-279"><a href="#cb6-279" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-280"><a href="#cb6-280" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb6-281"><a href="#cb6-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-282"><a href="#cb6-282" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregamento das bibliotecas de análise e formatação</span></span>
<span id="cb6-283"><a href="#cb6-283" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leem)</span>
<span id="cb6-284"><a href="#cb6-284" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb6-285"><a href="#cb6-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-286"><a href="#cb6-286" aria-hidden="true" tabindex="-1"></a><span class="co"># Importação dos dados a partir do arquivo CSV</span></span>
<span id="cb6-287"><a href="#cb6-287" aria-hidden="true" tabindex="-1"></a>tabela_importada <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dados_compactacao.csv"</span>)</span>
<span id="cb6-288"><a href="#cb6-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-289"><a href="#cb6-289" aria-hidden="true" tabindex="-1"></a><span class="co"># Extração da coluna de dados como um vetor numérico</span></span>
<span id="cb6-290"><a href="#cb6-290" aria-hidden="true" tabindex="-1"></a>grau_compactacao <span class="ot">&lt;-</span> tabela_importada<span class="sc">$</span>Compactacao</span>
<span id="cb6-291"><a href="#cb6-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-292"><a href="#cb6-292" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilização da função new_leem para classificar como variável contínua (2)</span></span>
<span id="cb6-293"><a href="#cb6-293" aria-hidden="true" tabindex="-1"></a>gc_leem <span class="ot">&lt;-</span> <span class="fu">new_leem</span>(grau_compactacao, <span class="at">variable =</span> <span class="dv">2</span>)</span>
<span id="cb6-294"><a href="#cb6-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-295"><a href="#cb6-295" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorganizando os 50 dados em 5 colunas de 10 linhas para exibição compacta</span></span>
<span id="cb6-296"><a href="#cb6-296" aria-hidden="true" tabindex="-1"></a>tabela_exibicao <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">matrix</span>(grau_compactacao, <span class="at">ncol =</span> <span class="dv">5</span>, <span class="at">byrow =</span> <span class="cn">FALSE</span>))</span>
<span id="cb6-297"><a href="#cb6-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-298"><a href="#cb6-298" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibindo os dados brutos de forma formatada com a função kable</span></span>
<span id="cb6-299"><a href="#cb6-299" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabela_exibicao, </span>
<span id="cb6-300"><a href="#cb6-300" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="st">"c"</span>, </span>
<span id="cb6-301"><a href="#cb6-301" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Ensaios 1 a 10"</span>, <span class="st">"Ensaios 11 a 20"</span>, <span class="st">"Ensaios 21 a 30"</span>, <span class="st">"Ensaios 31 a 40"</span>, <span class="st">"Ensaios 41 a 50"</span>),</span>
<span id="cb6-302"><a href="#cb6-302" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Base de Dados Importada - Grau de Compactação (%)"</span>)</span>
<span id="cb6-303"><a href="#cb6-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-304"><a href="#cb6-304" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-305"><a href="#cb6-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-306"><a href="#cb6-306" aria-hidden="true" tabindex="-1"></a><span class="fu">### Tabulação de Frequências (Consciência do Processo)</span></span>
<span id="cb6-307"><a href="#cb6-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-308"><a href="#cb6-308" aria-hidden="true" tabindex="-1"></a>Ao executar a função <span class="in">`tabfreq()`</span>, o algoritmo busca o valor mínimo (93.9%) e o máximo (101.1%), define a Amplitude Total da amostra e utiliza equações empíricas (como a regra de Sturges $k \approx 1 + 3,322 \log n$) para encontrar um número ideal de classes de intervalo. Com as classes definidas, o algoritmo executa somatórios condicionais, contando quantas amostras caem dentro de cada intervalo.</span>
<span id="cb6-309"><a href="#cb6-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-312"><a href="#cb6-312" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-313"><a href="#cb6-313" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tabela-freq</span></span>
<span id="cb6-314"><a href="#cb6-314" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-315"><a href="#cb6-315" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb6-316"><a href="#cb6-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-317"><a href="#cb6-317" aria-hidden="true" tabindex="-1"></a><span class="co"># Geração e plotagem nativa da tabela de distribuição de frequências</span></span>
<span id="cb6-318"><a href="#cb6-318" aria-hidden="true" tabindex="-1"></a>tabela_gc <span class="ot">&lt;-</span> <span class="fu">tabfreq</span>(gc_leem)</span>
<span id="cb6-319"><a href="#cb6-319" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabela_gc<span class="sc">$</span>table, <span class="at">align =</span> <span class="st">"c"</span>, <span class="at">caption =</span> <span class="st">"Tabela de Distribuição de Frequência - GC (%)"</span>)</span>
<span id="cb6-320"><a href="#cb6-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-321"><a href="#cb6-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-322"><a href="#cb6-322" aria-hidden="true" tabindex="-1"></a>A tabulação já nos adianta o primeiro alerta: embora a maior densidade dos dados ($F_i$) esteja bem alocada nas faixas superiores a 95%, existe uma parcela de ensaios que caiu nas classes mais baixas do conjunto.</span>
<span id="cb6-323"><a href="#cb6-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-324"><a href="#cb6-324" aria-hidden="true" tabindex="-1"></a><span class="fu">### Síntese Descritiva: Posição, Dispersão e Forma</span></span>
<span id="cb6-325"><a href="#cb6-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-326"><a href="#cb6-326" aria-hidden="true" tabindex="-1"></a>Para validar o maciço, não basta olhar para a tabela. Precisamos quantificar matematicamente o comportamento através dos momentos estatísticos. O código abaixo automatiza as equações dos Capítulos 3 e 4.</span>
<span id="cb6-327"><a href="#cb6-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-330"><a href="#cb6-330" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-331"><a href="#cb6-331" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: medidas</span></span>
<span id="cb6-332"><a href="#cb6-332" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-333"><a href="#cb6-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-334"><a href="#cb6-334" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Medidas de Posição</span></span>
<span id="cb6-335"><a href="#cb6-335" aria-hidden="true" tabindex="-1"></a>gc_media <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">mean</span>(grau_compactacao))</span>
<span id="cb6-336"><a href="#cb6-336" aria-hidden="true" tabindex="-1"></a>gc_mediana <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">median</span>(grau_compactacao))</span>
<span id="cb6-337"><a href="#cb6-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-338"><a href="#cb6-338" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Medidas de Dispersão</span></span>
<span id="cb6-339"><a href="#cb6-339" aria-hidden="true" tabindex="-1"></a>gc_desvio <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">sd</span>(grau_compactacao))</span>
<span id="cb6-340"><a href="#cb6-340" aria-hidden="true" tabindex="-1"></a>gc_var <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">var</span>(grau_compactacao))</span>
<span id="cb6-341"><a href="#cb6-341" aria-hidden="true" tabindex="-1"></a>gc_cv <span class="ot">&lt;-</span> (gc_desvio <span class="sc">/</span> gc_media) <span class="sc">*</span> <span class="dv">100</span> </span>
<span id="cb6-342"><a href="#cb6-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-343"><a href="#cb6-343" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Medidas de Forma (Cálculo via Momentos Centrais)</span></span>
<span id="cb6-344"><a href="#cb6-344" aria-hidden="true" tabindex="-1"></a>n_amostras <span class="ot">&lt;-</span> <span class="fu">length</span>(grau_compactacao)</span>
<span id="cb6-345"><a href="#cb6-345" aria-hidden="true" tabindex="-1"></a><span class="co"># Somatório (xi - x_barra)^3</span></span>
<span id="cb6-346"><a href="#cb6-346" aria-hidden="true" tabindex="-1"></a>momento3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n_amostras</span>
<span id="cb6-347"><a href="#cb6-347" aria-hidden="true" tabindex="-1"></a>desvio_cubico <span class="ot">&lt;-</span> (<span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n_amostras)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb6-348"><a href="#cb6-348" aria-hidden="true" tabindex="-1"></a>gc_assimetria <span class="ot">&lt;-</span> momento3 <span class="sc">/</span> desvio_cubico</span>
<span id="cb6-349"><a href="#cb6-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-350"><a href="#cb6-350" aria-hidden="true" tabindex="-1"></a><span class="co"># Somatório (xi - x_barra)^4</span></span>
<span id="cb6-351"><a href="#cb6-351" aria-hidden="true" tabindex="-1"></a>momento4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n_amostras</span>
<span id="cb6-352"><a href="#cb6-352" aria-hidden="true" tabindex="-1"></a>desvio_quarto <span class="ot">&lt;-</span> (<span class="fu">sum</span>((grau_compactacao <span class="sc">-</span> gc_media)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n_amostras)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb6-353"><a href="#cb6-353" aria-hidden="true" tabindex="-1"></a>gc_curtose <span class="ot">&lt;-</span> (momento4 <span class="sc">/</span> desvio_quarto) <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb6-354"><a href="#cb6-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-355"><a href="#cb6-355" aria-hidden="true" tabindex="-1"></a><span class="co"># Consolidação dos Resultados</span></span>
<span id="cb6-356"><a href="#cb6-356" aria-hidden="true" tabindex="-1"></a>estatisticas_gc <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-357"><a href="#cb6-357" aria-hidden="true" tabindex="-1"></a>  Parâmetro <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Média (%)"</span>, <span class="st">"Mediana (%)"</span>, <span class="st">"Desvio Padrão (%)"</span>, </span>
<span id="cb6-358"><a href="#cb6-358" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Variância (%²)"</span>, <span class="st">"CV (%)"</span>, <span class="st">"Assimetria"</span>, <span class="st">"Curtose"</span>),</span>
<span id="cb6-359"><a href="#cb6-359" aria-hidden="true" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">round</span>(<span class="fu">c</span>(gc_media, gc_mediana, gc_desvio, </span>
<span id="cb6-360"><a href="#cb6-360" aria-hidden="true" tabindex="-1"></a>                      gc_var, gc_cv, gc_assimetria, gc_curtose), <span class="dv">3</span>)</span>
<span id="cb6-361"><a href="#cb6-361" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-362"><a href="#cb6-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-363"><a href="#cb6-363" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(estatisticas_gc, <span class="at">align =</span> <span class="st">"c"</span>, <span class="at">caption =</span> <span class="st">"Estatísticas Descritivas Consolidadas - GC"</span>)</span>
<span id="cb6-364"><a href="#cb6-364" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-365"><a href="#cb6-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-366"><a href="#cb6-366" aria-hidden="true" tabindex="-1"></a>**Análise Crítica dos Resultados:**</span>
<span id="cb6-367"><a href="#cb6-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-368"><a href="#cb6-368" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Centro Equilibrado:** O algoritmo obteve uma média de **97,14%** e mediana de **97,15%**. A proximidade quase exata dessas duas grandezas confirma que não há "puxões" fortes (outliers severos) dominando o centro dos dados. </span>
<span id="cb6-369"><a href="#cb6-369" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Homogeneidade de Execução:** O Coeficiente de Variação (CV) foi extremamente baixo (**1,86%**). Tal valor atesta que a frota de maquinário (rolos compactadores, caminhões-pipa e motoniveladoras) executou o serviço com padrão uniforme de energia em quase toda a praça de trabalho.</span>
<span id="cb6-370"><a href="#cb6-370" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Diagnóstico de Forma:** </span>
<span id="cb6-371"><a href="#cb6-371" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>A **Assimetria levemente positiva (0,157)** indica uma distribuição quase simétrica, mas com uma ínfima tendência de cauda para a direita (algumas amostras com compactação excepcional puxando levemente a curva).</span>
<span id="cb6-372"><a href="#cb6-372" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>A **Curtose negativa (-0,735)** revela uma distribuição platicúrtica. Ou seja, em vez de se concentrar aguda e perigosamente no centro, os dados estão distribuídos de forma mais constante, com caudas mais curtas, o que estatisticamente diminui a chance da ocorrência de desvios drásticos e isolados.</span>
<span id="cb6-373"><a href="#cb6-373" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-374"><a href="#cb6-374" aria-hidden="true" tabindex="-1"></a><span class="fu">### Apresentação Gráfica e Decisão de Engenharia</span></span>
<span id="cb6-375"><a href="#cb6-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-376"><a href="#cb6-376" aria-hidden="true" tabindex="-1"></a>**Análise Gráfica de Dispersão e Outliers (Boxplot)**</span>
<span id="cb6-377"><a href="#cb6-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-378"><a href="#cb6-378" aria-hidden="true" tabindex="-1"></a>Para validar visualmente as métricas de dispersão, assimetria e curtose calculadas anteriormente, a ferramenta estatística mais robusta é o *Boxplot* (Diagrama de Caixa). Ele segmenta os dados em quartis (blocos de 25% da amostra) e permite identificar imediatamente a presença de anomalias operacionais (*outliers*) e o achatamento da distribuição.</span>
<span id="cb6-379"><a href="#cb6-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-382"><a href="#cb6-382" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-383"><a href="#cb6-383" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: grafico-boxplot</span></span>
<span id="cb6-384"><a href="#cb6-384" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-385"><a href="#cb6-385" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: "center"</span></span>
<span id="cb6-386"><a href="#cb6-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-387"><a href="#cb6-387" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuração do Boxplot em R</span></span>
<span id="cb6-388"><a href="#cb6-388" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(grau_compactacao,</span>
<span id="cb6-389"><a href="#cb6-389" aria-hidden="true" tabindex="-1"></a>        <span class="at">horizontal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-390"><a href="#cb6-390" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#d0e1f9"</span>,</span>
<span id="cb6-391"><a href="#cb6-391" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"#1e3d59"</span>,</span>
<span id="cb6-392"><a href="#cb6-392" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Grau de Compactação (%)"</span>,</span>
<span id="cb6-393"><a href="#cb6-393" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot do Grau de Compactação"</span>)</span>
<span id="cb6-394"><a href="#cb6-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-395"><a href="#cb6-395" aria-hidden="true" tabindex="-1"></a><span class="co"># Adicionando o Limite de Especificação para referência</span></span>
<span id="cb6-396"><a href="#cb6-396" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">95.0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb6-397"><a href="#cb6-397" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="st">"Limite Mín (95%)"</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb6-398"><a href="#cb6-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-399"><a href="#cb6-399" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-400"><a href="#cb6-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-401"><a href="#cb6-401" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>A linha escura que corta a caixa no meio representa a Mediana (97,15%). O fato de ela estar exatamente no centro do retângulo azul confirma uma *Assimetria quase nula*.</span>
<span id="cb6-402"><a href="#cb6-402" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>O tamanho estreito da caixa retangular (que concentra os 50% centrais de todos os ensaios) comprova visualmente o baixo Coeficiente de Variação (CV). O maquinário compactou quase todo o material dentro de uma faixa de energia muito previsível.</span>
<span id="cb6-403"><a href="#cb6-403" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Os traços laterais (conhecidos como "bigodes") indicam as caudas da distribuição. Como estão curtos e não vemos pequenos pontos isolados para fora deles, confirmamos a *Curtose negativa*, ou seja, uma distribuição achatada e sem outliers caindo fora do padrão esperado.</span>
<span id="cb6-404"><a href="#cb6-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-405"><a href="#cb6-405" aria-hidden="true" tabindex="-1"></a>**Distribuição dos Dados**</span>
<span id="cb6-406"><a href="#cb6-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-407"><a href="#cb6-407" aria-hidden="true" tabindex="-1"></a>O histograma sobreposto pelos limites de aceitação possui a resposta para a aprovação ou reprovação da camada pelo engenheiro fiscal.</span>
<span id="cb6-408"><a href="#cb6-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-411"><a href="#cb6-411" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-412"><a href="#cb6-412" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: histograma</span></span>
<span id="cb6-413"><a href="#cb6-413" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-414"><a href="#cb6-414" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: "center"</span></span>
<span id="cb6-415"><a href="#cb6-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-416"><a href="#cb6-416" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(grau_compactacao, </span>
<span id="cb6-417"><a href="#cb6-417" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">7</span>, </span>
<span id="cb6-418"><a href="#cb6-418" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#a8c0d8"</span>, </span>
<span id="cb6-419"><a href="#cb6-419" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"white"</span>,</span>
<span id="cb6-420"><a href="#cb6-420" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Análise da Distribuição do GC"</span>,</span>
<span id="cb6-421"><a href="#cb6-421" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Grau de Compactação alcançado (%)"</span>,</span>
<span id="cb6-422"><a href="#cb6-422" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequência (Nº de Ensaios)"</span>)</span>
<span id="cb6-423"><a href="#cb6-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-424"><a href="#cb6-424" aria-hidden="true" tabindex="-1"></a><span class="co"># Marcadores Críticos de Tomada de Decisão</span></span>
<span id="cb6-425"><a href="#cb6-425" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">95.0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># Limite Mínimo de Projeto</span></span>
<span id="cb6-426"><a href="#cb6-426" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> gc_media, <span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="co"># Desempenho Real</span></span>
<span id="cb6-427"><a href="#cb6-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-428"><a href="#cb6-428" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, </span>
<span id="cb6-429"><a href="#cb6-429" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Média Executada (97.1%)"</span>, <span class="st">"Limite Projeto - Mín 95%"</span>), </span>
<span id="cb6-430"><a href="#cb6-430" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"darkgreen"</span>, <span class="st">"red"</span>), </span>
<span id="cb6-431"><a href="#cb6-431" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb6-432"><a href="#cb6-432" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb6-433"><a href="#cb6-433" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-434"><a href="#cb6-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-435"><a href="#cb6-435" aria-hidden="true" tabindex="-1"></a>**O Veredito do Estudo de Caso:**</span>
<span id="cb6-436"><a href="#cb6-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-437"><a href="#cb6-437" aria-hidden="true" tabindex="-1"></a>As representações gráficas consolidam o diagnóstico operacional. O *Boxplot* atesta a homogeneidade geral do serviço, comprovando que não existem *outliers* decorrentes de falhas graves de execução. Contudo, o histograma evidencia que o limiar de projeto (95%) intercepta a cauda inferior da distribuição, afetando o primeiro bloco de frequências.</span>
<span id="cb6-438"><a href="#cb6-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-439"><a href="#cb6-439" aria-hidden="true" tabindex="-1"></a>Observando o banco de dados e a área sob o gráfico, constata-se que, apesar do serviço excelente na média (Média &gt; 97% e CV baixíssimo), ocorreram **6 ensaios reprovados** (valores abaixo de 95%, perfazendo 12% da amostra). O engenheiro fiscal responsável não precisa rejeitar todo o lote, mas deve solicitar a **recompactação setorial** nos pontos específicos onde esses resultados foram obtidos. Essa intervenção é necessária para maximizar confiabilidade estrutural antes da liberação do aterro para a próxima camada.</span>
<span id="cb6-440"><a href="#cb6-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-441"><a href="#cb6-441" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🧠 Considerações Finais</span></span>
<span id="cb6-442"><a href="#cb6-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-443"><a href="#cb6-443" aria-hidden="true" tabindex="-1"></a>O presente relatório demonstrou a importância da Estatística Descritiva como ferramenta essencial para o controle de qualidade na Engenharia Civil. A revisão teórica embasou a aplicação computacional no RStudio com o pacote leem, comprovando que o uso de rotinas programadas otimiza o tratamento de dados e garante maior confiabilidade aos resultados, substituindo procedimentos manuais.</span>
<span id="cb6-444"><a href="#cb6-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-445"><a href="#cb6-445" aria-hidden="true" tabindex="-1"></a>No estudo de caso sobre o Grau de Compactação, a aplicação integrada das medidas de posição, dispersão e forma foi determinante para a tomada de decisão. A análise restrita à média indicaria a aceitação total do serviço; porém, a avaliação da variância aliada ao histograma permitiu identificar desvios específicos, embasando a recomendação de correção pontual em 12% da área analisada. Assim, os objetivos da prática foram atingidos, evidenciando que o domínio conjunto de conceitos estatísticos e ferramentas computacionais é fundamental para análises técnicas mais seguras e criteriosas no canteiro de obras.</span>
<span id="cb6-446"><a href="#cb6-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-447"><a href="#cb6-447" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📖 Referências</span></span>
</code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>